# Generated by Django 6.0.4 on 2026-05-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('numero_permis', models.CharField(max_length=50, unique=True, verbose_name='N° Permis')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_zone', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('tarif_base', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tarif de base (MAD)')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(max_length=20, unique=True, verbose_name="Plaque d'immatriculation")),
                ('disponibilite', models.BooleanField(default=True, verbose_name='Disponible')),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('en_course', 'En course'), ('hors_service', 'Hors service')], default='libre', max_length=20, verbose_name='Statut')),
                ('date_mise_circulation', models.DateField(verbose_name='Date de mise en circulation')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.chauffeur', verbose_name='Chauffeur assigné')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.zone', verbose_name="Zone d'opération")),
            ],
            options={
                'verbose_name': 'Taxi',
                'verbose_name_plural': 'Taxis',
                'ordering': ['plaque'],
            },
        ),
    ]
